version: 2.1

orbs:
  node: circleci/node@4.1
  docker: circleci/docker@1.6.0

jobs:
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - SSH_KEY_FINGERPRINT_WEB_BAN_HOA
      - run:
          name: Deploy to VPS
          command: ssh -v -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER 'chmod +x ./backend_cua_Tan.sh && ./backend_cua_Tan.sh'

workflows:
  cicd-ing:
    jobs:
      - deploy:
          context: fs
          filters:
            branches:
              only:
                - ui_user
